# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1imcqSSb3GqywlcI-IsT4lTgPADYu7Q60
"""

import math

# Nhập giá trị hệ số a, b, c từ người dùng
a = float(input("Nhập hệ số a: "))
b = float(input("Nhập hệ số b: "))
c = float(input("Nhập hệ số c: "))

# Kiểm tra điều kiện a = 0
if a == 0:
    if b != 0:
        # Phương trình bậc nhất bx + c = 0
        x = -c / b
        print(f"Phương trình bậc nhất có nghiệm x = {x}")
    else:
        # a = 0 và b = 0
        print("Phương trình không hợp lệ.")
else:
    # Tính delta
    delta = b**2 - 4*a*c

    # Phân loại nghiệm dựa trên delta
    if delta > 0:
        x1 = (-b + math.sqrt(delta)) / (2*a)
        x2 = (-b - math.sqrt(delta)) / (2*a)
        print(f"Phương trình có hai nghiệm phân biệt x1 = {x1} và x2 = {x2}")
    elif delta == 0:
        x = -b / (2*a)
        print(f"Phương trình có nghiệm kép x = {x}")
    else:
        print("Phương trình vô nghiệm trong tập số thực.")

n = int(input("Enter a positive integer:"))
print(n)

s = 0  # biến số dùng để lưu tổng
for i in range(1, n + 1):
    s += i

print(f"The sum of 1 to {n} is {s}")